name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1

    - name: Install dependencies
      run: nuget restore ./BareLink.sln
      
    - name: Build Tests
      run: msbuild ./BareLink.sln /t:Build /p:Configuration=Release
      
    - name: Run Tests
      run: vstest.console.exe BareLink.Test/bin/Release/netcoreapp3.1/BareLink.Test.dll /Logger:trx

    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
      with:
        reporter: dotnet-trx
        name: Unit Tests
        path: 'TestResults/*.trx'
