name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64

    - name: Install dependencies
      run: nuget restore ./BareLink.sln

    - name: Build App
      run: msbuild ./BareLink/BareLink.csproj /t:PackageForAndroid /p:Configuration=Release
      
    - name: Build Tests
      run: msbuild ./BareLink.Test/BareLink.Test.csproj /t:Build /p:Configuration=Release
      
    - name: Install NUnit.ConsoleRunner
      run: nuget install NUnit.ConsoleRunner -Version 3.13.0 -DirectDownload -OutputDirectory .
        
    - name: Run UnitTests
      run: ./NUnit.ConsoleRunner.3.13.0/tools/nunit3-console.exe  ./BareLink.Test/bin/Release/BareLink.Test.dll
      
    - name: Test Report
      uses: dorny/test-reporter@v1.5.0
      if: success() || failure()
      with:
        name: Unit tests
        reporter: dotnet-trx
        path: TestResult.xml
